{
 "title": "JupyterHub",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>JupyterHub\n</span>\n</div>"
   }
  },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Users" } },
   "yaxes": [
    { "format": "Users" }
   ],
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers)",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Current Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers)",
     "legendFormat": "Current Users"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((jupyterhub_running_servers / jupyterhub_total_users) * 100)",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jupyterhub_total_users)", "legendFormat": "Current Users" }
   ]
  },
  {
   "title": "Minimum Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers)",
     "legendFormat": "Minimum Users"
    }
   ]
  },
  {
   "title": "Average Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers)",
     "legendFormat": "Average Users"
    }
   ]
  },
  {
   "title": "Maximum Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers)",
     "legendFormat": "Maximum Users"
    }
   ]
  },
  {
   "title": "User Growth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Users" } },
   "yaxes": [
    { "format": "Users" }
   ],
   "targets": [
    { "expr": "sum(jupyterhub_total_users)", "legendFormat": "Total Users" }
   ]
  }
 ]
}